; Pac-Man (NES) multi-revision native ca65 source entrypoint
; Module order is ROM order and must not change

.setcpu "6502"

.include "revisions/profile_ids.inc"
.include "memory/ram.inc"
.include "memory/hardware.inc"
.include "memory/constants.inc"
.include "macros/memory.inc"
.include "macros/ppu.inc"
.include "macros/hud.inc"
.include "macros/actors.inc"
.include "data/active_tables.inc"

.include "system/boot_and_frame.asm"
.include "game/title/screen.asm"
.include "game/title/attract_intro.asm"
.include "game/title/attract_chase.asm"
.include "game/round/gameplay_loop.asm"
.include "game/round/ready.asm"
.include "game/round/transitions.asm"
.include "game/round/setup.asm"
.include "game/round/runtime.asm"
.include "game/pacman_movement.asm"
.include "game/ghosts/navigation.asm"
.include "game/ghosts/house.asm"
.include "rendering/actors/animation.asm"
.include "rendering/actors/oam.asm"
.include "rendering/ppu_updates.asm"
.include "game/scoring.asm"
.include "rendering/tile_coordinates.asm"
.include "rendering/maze_rendering.asm"
.include "rendering/hud/score.asm"
.include "game/turn_candidates.asm"
.include "rendering/hud/status.asm"
.include "game/intermission/setup.asm"
.include "game/intermission/scenes.asm"
.include "game/intermission/actors.asm"
.include "game/intermission/animation.asm"
.include "data/stage_parameters.asm"
.include "data/maze.asm"
.include "audio/engine.asm"
.include "audio/streams.asm"
.include "data/tail_and_vectors.asm"
